version: "3"
services:
  service-1:
    build: ./services/service-1 
    depends_on:
      - postgres
    environment:       
        PG_HOST: postgres
  service-2:
    build: ./services/service-2 
    depends_on:
      - postgres
    environment:       
        PG_HOST: postgres    
  postgres:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  sut:
    build: ./services/service-1
    depends_on:
      - service-1
    environment:
      SERVICE_HOST: service-1    
    command: npm run test