version: "3"
services:
  service-1:
    build: ./service-1
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:       
      PG_HOST: postgres 
  postgres:
    image: postgres:12.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
