version: "3"
services:
  service-1:
    image: ACOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/service-1
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:       
      PG_HOST: postgres
  service-2:
    image: ACOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/service-2
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:       
      PG_HOST: postgres    
  postgres:
    image: postgres:12.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres